name: Welcome
version: '${project.version}'
main: com.swjtu.welcome.Welcome
api-version: 1.18

commands:
  getEssentialItem:
    description: "Get essential item"
    usage: /getEssentialItem
    permission: getEssentialItem.getEssentialItem

  maskChecker:
    description: "Check mask"
    usage: /maskChecker
    permission: maskChecker.maskChecker
  ScamScenarios:
    description: "Scam scenarios"
    usage: /ScamScenarios
    permission: ScamScenarios.ScamScenarios
  GateSetter:
    description: "Gate setter"
    usage: /GateSetter
    permission: GateSetter.GateSetter
  setReportStatus:
    description: "Set report status"
    usage: /setReportStatus
    permission: setReportStatus.setReportStatus
  MultiCmdExec:
    description: "Multi command executor"
    usage: /MultiCmdExec
    permission: MultiCmdExec.MultiCmdExec
  BlockSetter:
    description: "Block setter"
    usage: /BlockSetter
    permission: BlockSetter.BlockSetter
  lineMaterial:
    description: "Line setter"
    usage: /lineMaterial
    permission: LineSetter.LineSetter
  ReloadConfig:
    description: "Reload config"
    usage: /ReloadConfig
    permission: ReloadConfig.ReloadConfig

permissions:
  getEssentialItem.getEssentialItem:
    description: "Allows the user to use the /getEssentialItem command"
    default: true
    maskChecker.maskChecker:
      description: "Allows the user to use the /maskChecker command"
      default: true

    ScamScenarios.ScamScenarios:
      description: "Allows the user to use the /ScamScenarios command"
      default: true

    GateSetter.GateSetter:
      description: "Allows the user to use the /GateSetter command"
      default: true

    setReportStatus.setReportStatus:
        description: "Allows the user to use the /setReportStatus command"
        default: true
    MultiCmdExec.MultiCmdExec:
        description: "Allows the user to use the /MultiCmdExec command"
        default: true
    BlockSetter:
        description: "Allows the user to use the /BlockSetter command"
        default: true
    LineSetter:
        description: "Allows the user to use the /LineSetter command"
        default: true
    ReloadConfig:
        description: "Allows the user to use the /ReloadConfig command"
        default: true
